const exchanges = [
  {
    id: "NSE",
    name: "National Stock Exchange",
    country: "India",
    latitude: 19.0600,
    longitude: 72.8646,
    timezone: "Asia/Kolkata",
    open_time: "09:15",
    close_time: "15:30",
    index_name: "NIFTY 50",
    yahoo_symbol: "^NSEI",
    currency: "₹",
    currency_code: "INR",
  },
  {
    id: "BSE",
    name: "Bombay Stock Exchange",
    country: "India",
    latitude: 18.9300,
    longitude: 72.8333,
    timezone: "Asia/Kolkata",
    open_time: "09:15",
    close_time: "15:30",
    index_name: "SENSEX",
    yahoo_symbol: "^BSESN",
    currency: "₹",
    currency_code: "INR",
  },
  {
    id: "NYSE",
    name: "New York Stock Exchange",
    country: "USA",
    latitude: 40.7069,
    longitude: -74.0113,
    timezone: "America/New_York",
    open_time: "09:30",
    close_time: "16:00",
    index_name: "S&P 500",
    yahoo_symbol: "^GSPC",
    currency: "$",
    currency_code: "USD",
  },
  {
    id: "NASDAQ",
    name: "NASDAQ",
    country: "USA",
    latitude: 40.7589,
    longitude: -73.9851,
    timezone: "America/New_York",
    open_time: "09:30",
    close_time: "16:00",
    index_name: "NASDAQ Composite",
    yahoo_symbol: "^IXIC",
    currency: "$",
    currency_code: "USD",
  },
  {
    id: "LSE",
    name: "London Stock Exchange",
    country: "UK",
    latitude: 51.5138,
    longitude: -0.0983,
    timezone: "Europe/London",
    open_time: "08:00",
    close_time: "16:30",
    index_name: "FTSE 100",
    yahoo_symbol: "^FTSE",
    currency: "£",
    currency_code: "GBP",
  },
  {
    id: "TSE",
    name: "Tokyo Stock Exchange",
    country: "Japan",
    latitude: 35.6811,
    longitude: 139.7788,
    timezone: "Asia/Tokyo",
    open_time: "09:00",
    close_time: "15:00",
    index_name: "Nikkei 225",
    yahoo_symbol: "^N225",
    currency: "¥",
    currency_code: "JPY",
  },
  {
    id: "SSE",
    name: "Shanghai Stock Exchange",
    country: "China",
    latitude: 31.2383,
    longitude: 121.5015,
    timezone: "Asia/Shanghai",
    open_time: "09:30",
    close_time: "15:00",
    index_name: "SSE Composite",
    yahoo_symbol: "000001.SS",
    currency: "¥",
    currency_code: "CNY",
  },
  {
    id: "HKEX",
    name: "Hong Kong Stock Exchange",
    country: "Hong Kong",
    latitude: 22.2841,
    longitude: 114.1583,
    timezone: "Asia/Hong_Kong",
    open_time: "09:30",
    close_time: "16:00",
    index_name: "Hang Seng",
    yahoo_symbol: "^HSI",
    currency: "HK$",
    currency_code: "HKD",
  },
  {
    id: "ASX",
    name: "Australian Securities Exchange",
    country: "Australia",
    latitude: -33.8643,
    longitude: 151.2078,
    timezone: "Australia/Sydney",
    open_time: "10:00",
    close_time: "16:00",
    index_name: "S&P/ASX 200",
    yahoo_symbol: "^AXJO",
    currency: "A$",
    currency_code: "AUD",
  },
  {
    id: "TSX",
    name: "Toronto Stock Exchange",
    country: "Canada",
    latitude: 43.6483,
    longitude: -79.3817,
    timezone: "America/Toronto",
    open_time: "09:30",
    close_time: "16:00",
    index_name: "S&P/TSX Composite",
    yahoo_symbol: "^GSPTSE",
    currency: "C$",
    currency_code: "CAD",
  },
  {
    id: "DAX",
    name: "Frankfurt Stock Exchange",
    country: "Germany",
    latitude: 50.1155,
    longitude: 8.6778,
    timezone: "Europe/Berlin",
    open_time: "09:00",
    close_time: "17:30",
    index_name: "DAX Performance",
    yahoo_symbol: "^GDAXI",
    currency: "€",
    currency_code: "EUR",
  },
  {
    id: "Euronext",
    name: "Euronext Paris",
    country: "EU",
    latitude: 48.8688,
    longitude: 2.3415,
    timezone: "Europe/Paris",
    open_time: "09:00",
    close_time: "17:30",
    index_name: "CAC 40",
    yahoo_symbol: "^FCHI",
    currency: "€",
    currency_code: "EUR",
  },
  {
    id: "KRX",
    name: "Korea Exchange",
    country: "South Korea",
    latitude: 35.1384,
    longitude: 129.0667,
    timezone: "Asia/Seoul",
    open_time: "09:00",
    close_time: "15:30",
    index_name: "KOSPI",
    yahoo_symbol: "^KS11",
    currency: "₩",
    currency_code: "KRW",
  },
  {
    id: "SGX",
    name: "Singapore Exchange",
    country: "Singapore",
    latitude: 1.2801,
    longitude: 103.8509,
    timezone: "Asia/Singapore",
    open_time: "09:00",
    close_time: "17:00",
    index_name: "STI",
    yahoo_symbol: "^STI",
    currency: "S$",
    currency_code: "SGD",
  }
];

module.exports = exchanges;
